version: 2
builds:
  - binary: tfschema
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Update README
      - Update CHANGELOG
brews:
  - repository:
      owner: minamijoyo
      name: homebrew-tfschema
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Masayuki Morita"
      email: minamijoyo@gmail.com
    homepage: https://github.com/minamijoyo/tfschema
    description: "A schema inspector for Terraform / OpenTofu providers."
    skip_upload: auto
    test: |
      system "#{bin}/tfschema --version"
    install: |
      bin.install "tfschema"
